import argparse
from os import system

parser = argparse.ArgumentParser(description = "script to delete resources generated by laravel-phpfpm... template")

parser.add_argument("appName", nargs='?', metavar = "appName", type = str, help = "The name of the app resources to delete")

args = parser.parse_args()

resourceTypes = ['is', 'bc', 'deploy', 'dc', 'svc', 'route']
resources = [
    f'is/{args.appName}-frontend',
    f'is/{args.appName}-backend',
    f'bc/{args.appName}-frontend',
    f'bc/{args.appName}-backend',
    f'svc/{args.appName}-frontend',
    f'route/{args.appName}-frontend',
    f'svc/{args.appName}-backend',
    f'deployment/{args.appName}-frontend',
    f'deployment/{args.appName}-backend',
    f'dc/{args.appName}-mysql',
    f'dc/{args.appName}-redis',
    f'pvc/{args.appName}-mysql-storage',
    f'pvc/{args.appName}-redis-storage',
    f'secret/{args.appName}-app-key',
    f'cm/{args.appName}-backend-config'
]
command = f'oc delete '+' '.join(resources)

system(command)
